---
apiVersion: v1
kind: Pod
metadata:
  name: qwop-redis
  labels:
    app: qwop
    name: qwop-redis
spec:
  containers:
  - image: launcher.gcr.io/google/redis3
    name: redis
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: qwop-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    name: qwop-redis
