apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qwop-worker
  labels:
    app: qwop
    name: qwop-worker
spec:
  replicas: 64
  selector:
    matchLabels:
      name: qwop-worker
  template:
    metadata:
      labels:
        app: qwop
        name: qwop-worker
    spec:
      containers:
      - name: qwop-worker
        image: unixpickle/qwop-worker
        resources:
          limits:
            cpu: 1
            memory: 4G
        args:
        - "-envs=1"
        - "-standing-bonus=0.05"
